config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :products
  resources :categories
  resources :line_items
  resources :carts
  resources :orders

  get '/search', to: 'products#search'
  root 'products#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :line_items, dependent: :destroy
  validate :check_availability_of_product
  after_save :reduce_stock_of_product

  enum status: [:Processing, :Preparing, :Shipping, :Done, :Refund]


  def add_line_items_from_cart(cart)
    cart.line_items.each do |line_item|
      line_item.cart_id = nil
      self.line_items << line_item
      self.total_price += line_item.total_price.to_f
    end
   end

  private

  def reduce_stock_of_product
  	line_items = self.line_items
  	line_items.each do |line|
  		line.product.update_attribute(:stock, line.product.stock - line.quantity)
      line.product.update_attribute(:sales, line.product.sales + line.quantity)
  	end
  end

  def check_availability_of_product
  	line_items = self.line_items
  	line_items.each do |line|
  		unless line.product.stock >= line.quantity
  			self.errors.add(:quantity, "Out of stock")
      end
  	end
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  include CurrentCart
  before_action :set_cart, only: %i(new create)
  before_action :ensure_cart_isnt_empty, only: :create
  before_action :logged_in?

  def index
    if current_user.admin?
      @orders = Order.all
    else
      @orders = current_user.orders.all
    end
  end

  def create
    @order = Order.new
    @order.add_line_items_from_cart(@cart)
    @order.user_id = current_user.id

    if @order.save
      Cart.destroy(cookies.permanent[:cart_id])
      cookies.permanent[:cart_id] = nil
      flash[:success] = 'Thanks for order'
      CheckOutMailer.delay.check_out(current_user, @order)
      redirect_to root_path
    else
      @line_items = @cart.line_items
      render 'carts/index'
    end
  end

  def destroy
    @order = Order.find(params[:id])
    @order.user_id = nil
    if @order.destroy!
      flash[:success] = "Deleted!!"
      redirect_to :back
    else
      flash[:danger] = "Oops, something was wrong!"
    end

    authorize! :destroy, @order
  end

  def update
    @order = Order.find(params[:id])
    @order.status = params[:order][:status]
    if @order.save
      flash[:success] = "Updated!"
      redirect_to :back
    else
      flash[:danger] = "Oops, something was wrong!"
    end

    authorize! :update, @order
  end


  private

  def ensure_cart_isnt_empty
    if @cart.line_items.empty?
      flash[:danger] = 'Empty cart!!'
      redirect_to root_path
    end
  end


end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_order.html.erb
 
	
 <% order.line_items.each do |line| %>
   <% product = line.product %>
   <% rowspan_val = order.line_items.count %>
   <tr>

   <% if line.product.id == order.line_items.first.product.id %>
     <td rowspan="<%=rowspan_val%>", class="vertical-center"><%= order.id %></td>
   <% end %>

   <td width="400">
     <%= link_to image_tag(product.small_image_url), product %>
     <%= link_to product.title, product %> 
   </td>

   <td class="vertical-center">
   	 <%= line.quantity %>
   </td>

   <% if line.product.id == order.line_items.first.product.id %>
       <td rowspan="<%=rowspan_val%>" class="vertical-center">
       <%= number_to_currency(order.total_price) %>	
       </td>
    <% end %>

     <% if current_user.admin? %>

       <td rowspan="<%=rowspan_val%>" class="vertical-center">
         <% if can? :update, order %>
         
          <%= form_for order do |f| %>
             <div class="input-field">
             <%= f.select :status, options_for_select(Order.statuses.keys, order.status) %>
             </div>
           
             <%= f.submit "Update", class: "btn", id: "btn-update" %>

          <% end %>

          <% end %> <!-- end if -->

          
          <% if can? :destroy, order %>

             <%= button_to 'Delete', order_path(order), method: :delete, data: {confirm: "You sure?"}, class: "btn", id: "btn-delete"  %>
          <% end %>

       </td>  
      

      <% else %>
         <td rowspan="<%=rowspan_val%>" class="vertical-center">
            <%= order.status %>
         </td>

      <% end %>
   </tr>

<% end %>

app/views/orders/index.html.erb
<h1> All orders </h1>

<table class="bordered">
	<thead>
		<td>Order ID</td>
		<td>Product</td>
		<td>Quantity</td>
		<td>Total price</td>
		<td>Shipping status</td>
		<% if current_user.admin? %>
		<% end %>
	</thead>

	<tbody>

		<% if @orders.any? %>
		  <% @orders.each do |order| %>
		  	<%= render order %>
		  <% end %>
		<% end %>
		
	</tbody>

</table>