config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :products
  resources :categories
  resources :line_items
  resources :carts
  resources :orders

  get '/search', to: 'products#search'
  root 'products#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_header.html.erb
        <nav class="nav">
          <div class="nav-wrapper">

          <div class="main-logo"><%= link_to image_tag("logo", size: "169x20"), root_path, class: "brand-logo" %></div>

          <a href = "" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>

         

      	  <ul id="nav-mobile" class="right hide-on-med-and-down">
      	    <%= render 'layouts/header_content' %>


      	  </ul>


          <ul class="side-nav" id="mobile-demo">

               <%= render 'layouts/header_content' %>
          </ul>
          </div>

          

        </nav>

app/views/layouts/_header_content.html.erb
            <li> 
              <%=link_to('<i class="material-icons left">home</i>Home'.html_safe, root_path) %> 
            </li>

            <li>
                <%=link_to('<i class="material-icons left">shopping_cart</i> My cart'.html_safe, carts_path) %>
            </li>

            <% if current_user %>

      	    <li>  
               <%=link_to('<i class="material-icons left">account_circle</i>Profile'.html_safe, edit_user_registration_path) %>
            </li>

            <li>
                <%=link_to('<i class="material-icons left">store</i>My products'.html_safe, new_product_path) %>
            </li>

            <% if current_user.admin? %>
              <li>
                  <%=link_to('<i class="material-icons left">reorder</i>Manage orders'.html_safe, orders_path) %>
              </li>
            <% else %>
              <li>
                  <%=link_to('<i class="material-icons left">reorder</i> Orders status'.html_safe, orders_path) %>
              </li>
            <% end %>

            <li>  
              <%=link_to('<i class="material-icons left">exit_to_app
</i> Log out'.html_safe, destroy_user_session_path, method: 'delete') %> 
            </li>

            <% else %>
              <li>            
                <%=link_to('<i class="material-icons left">check_circle</i> Sign up'.html_safe,  new_user_registration_path) %> 
              </li>            
              <li>  
              <%=link_to('<i class="material-icons left">person</i> Log in'.html_safe, new_user_session_path) %> 
            </li>


            <% end %>

app/views/layouts/_loader.html.erb
<div id="loader-wrapper">
    <div id="loader"></div>
 
    <div class="loader-section section-left"></div>
    <div class="loader-section section-right"></div>
 
</div>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_search_form.html.erb
<!--<%= form_tag("/search", method: "get") do %>
  <%= text_field_tag :q, nil, class: 'sb-search-input', placeholder: "Enter your search term ..." %>
  <%= submit_tag("Search", class: 'sb-search-submit') %>
   <span class="sb-icon-search"></span>
<% end %>-->
<div class="row">
	<div class="col m12 s12">
		<%= form_tag("/search", method: "get") do %>
			<div class= "input-field col s12" >
    		<%= text_field_tag :q, nil, placeholder: "Enter your search term ..."%>
    		<label for="search"><i class="material-icons">search</i></label>
    		</div>
		<% end %>
	</div>
</div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->

app/views/layouts/_sidebar.html.erb
<div class="col m3 s12">
 	   
  <ul class="collapsible" data-collapsible="accordion">
    <li>
      <div class="collapsible-header"><i class="material-icons">turned_in</i>Categories</div>
      <div class="collapsible-body">  
      <ul>
        <% Category.all.each do |cate| %>         
		  <li class="collection-item"><h6><%=link_to(cate.name, cate) %></h6></li>
        <% end %>
        </ul>
       </div>
    </li>
  </ul>  
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    
    <%= display_meta_tags %>

    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <% render 'layouts/shim' %>
    <%= render 'layouts/rails_default' %>
    
    

  </head>

  <body>
    <%= render 'layouts/header' %>

    
    <div class = "container">
      
      <div class="row">
          <%= render 'layouts/sidebar' %>
          
      <div class="col s12 m9">

        <%= render 'layouts/search_form' %>
        
         <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
      
      <% end %>
        
        <%= yield %>
        </div>

      </div>
      
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>